---
title: "EdwardsBIO6100"
author: "Madelynn Edwards"
date: "Made on 2024-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## **Edwards HW Repository**


#### This is where I will be posting my homework links for each lab

*24 Jan 2024*

* This is the link for assignment 1: [link](Homework_02.html)

*31 Jan 2024*

* This is the link for the Regular Expression Puzzles assignment: [link](Homework_03.html)

*7 Feb 2024*

* This is the link for Homework number 4 (Atomic vectors): [link](Homework_04.html)

*14 Feb 2024*

* This is the link for Homework 5 (Matrices, lists, and data frames): [link](Homework_05.html)

*21 Feb 2024*

* This is the link for Homework 6 (Simulating and Fitting Data Distributions): [link](Homework_06.html)

*28 Feb 2024*

* This is the link for Homework 7 (Creating Fake Data Sets to Explore Hypotheses): [link](Homework_07.html)

*20 March 2024*

* This is the link for Homework 8 (Data manipulations using the dplyr package): [link](Homework_08.html) 

*27 March 2024*

* This is the link for Homework 9 (Organizing Code with Structured Programming): [link](Homework_09.html)
* Script with just functions: [link](HW_09_Script.R)

*3 April 2024*

* This is the link for Homework 10 (For loops and randomization tests): [link](Homework_10.html)

*10 April 2024*

* This is the link for Homework 11 (Batch processing): [link](HW_11_batchprocessing.R) I apologize for having to upload a script. For some reason I couldn't get R markdown to work with this code. The working directories couldn't be changed and the code I used in the script (which ran fine) wouldn't work in markdown.

*17 April 2024*

* This is the link for Homework 12 (Advanced ggplotting): [link](Homework_12.html)


